services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${PORT_PUB:-5000}:${PORT:-3000}"
    volumes:
      - ./uploads:/test-app/uploads
    env_file:
      - .env
